version: '3'
services:
  rpi-imager:
    build:
      dockerfile: Dockerfile.rpi-imager
  nginx:
    image: nginx:stable-alpine
    volumes:
      - .:/usr/share/nginx/html:ro
    ports:
      - 8080:80
