assets:
  - name: Google
    uri: https://google.com
    mimetype: webpage

  - name: Screenly Clock Widget
    uri: https://clock.srly.io
    mimetype: webpage

  - name: Hacker News
    uri: https://news.ycombinator.com
    mimetype: webpage
